### ISSUE TITLE
Biobank explorer even slower on master

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-app-biobank-explorer#110]
### How to Reproduce
Upload the data + meta data of the eric package  (get it on accept server via navigator) THIS DOES WORK NOW, YAY! It almost makes up for this issue
Then upload the most recent version of the app via the app manager (for instance this one: 
[molgenis-app-biobank-explorer.zip](https://github.com/molgenis/molgenis/files/3961420/molgenis-app-biobank-explorer.zip))
Add biobank explorer to menu
Open network tab in inspect
Go to biobank explorer

### Expected behavior
It loads in += 8 seconds (as in 8.2.4). For anonymous this should be around 30 seconds (which is a complete other issue)

### Observed behavior
It loads in 24-25 seconds. For anonymous this is += 40 seconds.

**Comment by jelmerveen** [comment]
performance gain has been implemented, closing this ticket
