### ISSUE TITLE
Biobank Explorer does not support localisation of the buttons

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-app-biobank-explorer#111]
### How to Reproduce
Edit the negotiator localisation in MOLGENIS

### Expected behaviour
The 'Go to sample / data negotiation' button adopts the new localised string

### Observed behaviour
The button does not honour the localised string.

**Comment by jelmerveen** [comment]
Buttons and links are now editable through the configuration screen.
