### ISSUE TITLE
Free text search is not shown in the list of active filters

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-app-biobank-explorer#13]
### How to Reproduce
- Select one of the facets
- Do a free text search with the search bar above the table

### Expected behavior
- There is a box showing the free text search next to the box for the active facet search
- The free text search can be reset with the reset button for the search criteria

### Observed behavior
- The free text search is not shown in the list of active filters
- Pressing the reset button doesn't reset the free text search

**Comment by jelmerveen** [comment]
Issue seems to be resolved looking at the tag from pull request that has been merged. Closing it for now
