### ISSUE TITLE
Search for ID does not work when there is a space before or after the ID

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-app-biobank-explorer#158]
### How to Reproduce
Paste the ID of a collection in the Search facet and add a space to simulate an accidental paste of a space.

### Expected behaviour
Whitespace should not make a difference and the card of the biobank containing the collection is shown

### Observed behaviour
The card of the biobank is not shown.

**Comment by jelmerveen** [comment]
Resolved
