### ISSUE TITLE
Rename search facet

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-app-biobank-explorer#159]
### How to Reproduce
Go to the Directory and look at the facets

### Expected behaviour
The facet for searching by name clearly indicates that it is limited to finding by name, id or acronym. E.g.
Lookup by name/acronym/id

### Observed behaviour
The facet says search which suggests a broader ability to search the database than just name, id or acronym

**Comment by jelmerveen** [comment]
facet says: search by name, id, acronym and press enter

As described in issue. Closing this for now
