### ISSUE TITLE
Search only for ID if the search term starts with bbmri-eric:

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-app-biobank-explorer#160]
### How to Reproduce
Search for a collection by id, e.g.:  bbmri-eric:ID:SE_1801
### Expected behaviour
Only the organisation / collection related to the ID is shown. The prefix bbmri-eric: should be recognised as a specific search.

### Observed behavior
The organisation / collection related to the ID is shown, but in addition the BBMRI-Omics biobank and the Central data collections collected by BBMRI-ERIC are shown because they match in the name search on the token bbmri.

**Comment by jelmerveen** [comment]
Resolved, it will also match on partial ID like: bbmri-eric:ID:EXT_Audu
