### ISSUE TITLE
Importing Demo data set result in error  

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-app-biobank-explorer#170]
### How to Reproduce
- Setup clean ( current version ) molgenis
- Import sample data set: https://github.com/molgenis/molgenis-app-biobank-explorer/tree/master/sample-data

### Expected behavior
Data is imported 

### Observed behavior
Error during import 

```
"Error! Your import failed:
Expression 'standards' syntax invalid."
```

**Comment by connoratrug** [comment]
Suspect the sample data set is not compatible with current molgenis version, maybe need for sample data set per (supported) molgenis version

**Comment by jelmerveen** [comment]
Model has been updated
