### ISSUE TITLE
Biobank explorer search functionality shows incomplete results

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-app-biobank-explorer#172]
### How to Reproduce
In the catalogue.bbmri.nl you search for HIV.

### Expected behavior
You expect to see all biobanks with collections containing 'HIV' in the name/description/acronym/diagnosis

### Observed behavior
You only see the _HIV Host genetics cohort Biobank_ because this biobank has 'HIV' in the name of the biobank and collections. While there are 3 more that have HIV as diagnosis (label contains 'HIV') or HIV in description and acronym

**Comment by jelmerveen** [comment]
This issue is fixed in the latest bbmri-directory app, search also applied to diagnosis now
