### ISSUE TITLE
Collection network and biobank network filters not shown when selected

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-app-biobank-explorer#174]
### How to Reproduce
Go to the catalogue.bbmri.nl and open the 'collection network' or 'biobank network' facet and select a network.

### Expected behavior
You want to see the selected networks as filter in the upper part of the screen where you can deselect them, as is shown for every filter.

### Observed behavior
For specifically the collection and biobank networks the filtered variables are not shown.

**Comment by jelmerveen** [comment]
Fixed in version 3.2.0
