### ISSUE TITLE
Directory shows all collections belonging to a biobank instead of only the ones matching the filters

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis-app-biobank-explorer#20]
## How to reproduce
search query: country AT, material Plasma
## Expected result 
ALL Austrian PLASMA collections 
## Actual result 
ALL collections (any material) of Austrian Biobanks (grouped by biobank) which contains at least one Plasma-collection.

**Comment by ConnorStroomberg** [comment]
Possibly same issue as [Filters and query results get out of sync ](https://github.com/molgenis/molgenis-app-biobank-explorer/issues/28)?

**Comment by djvanenckevort** [comment]
Different issue. The issue here is that the filter is not applied to to the list of collections when you open the biobank card.
