### ISSUE TITLE
Collection data is not rendered correctly in biobank details view

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-app-biobank-explorer#238]
### How to Reproduce
Open https://catalogue.bbmri.nl/menu/main/app-molgenis-app-biobank-explorer/#/biobank/bbmri-eric:ID:NL_AAAACXPKHAQOYACQK2ME25QAAI

### Expected behavior
Collection data is shown with its label

### Observed behavior
Collection data is shown as a json structure (e.g. { "label": "Biological samples", "uri": "#" })

**Comment by jelmerveen** [comment]
closed by #244
