### ISSUE TITLE
When selecting two diagnostic codes, only the second is shown as filter

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-app-biobank-explorer#278]
### How to Reproduce

* Go to directory-acc
* Go to diagnostic search
* Search for C19
* Select C19
* Search for C18
* Select C18

### Expected behavior

Two items are selected AND visible in the search wells that show filters selected

### Observed behavior

Only C19 is selected and shown in the filter

**Comment by jelmerveen** [comment]
Fixed in latest version
