### ISSUE TITLE
Filters and query results get out of sync

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-app-biobank-explorer#28]
### How to Reproduce
Load the sample data, open the explorer.
Open the country filter and select Malta. 
The Maltese biobank is shown.

Quickly deselect and reselect malta

### Expected behavior
When the loading is done, the Maltese biobank is shown

### Observed behavior
Often, when the loading is done, the complete list of biobanks are shown.

This happens because the last incoming result wins.
![untitled](https://user-images.githubusercontent.com/1523838/44200014-e022ea00-a145-11e8-8e14-e863147ca34a.png)

**Comment by fdlk** [comment]
Suggested solution:
Have at most one outstanding query to update the biobanks. (This is in fact a series of queries, but here we consider the whole attempt to update as one single query)

Observe the filters.
Discard the biobank results when they no longer match the filters.
When filter hasn't changed for a certain amount of time, and when there is no outstanding query, start a query for the current filter settings.

When a query returns, check if it corresponds with the current filter settings.
If it does, all is well. Store the results.
If it does not, fire a new query for current filter settings.

**Comment by ConnorStroomberg** [comment]
What about 'simply' blocking user events ( combined with debouncing to keep a responsive UI) while requests are outstanding ?
