### ISSUE TITLE
Back button sends you to literal previous page instead of overview

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-app-biobank-explorer#287]
### How to Reproduce
1. Go to https://directory.bbmri-eric.eu/#/biobank/bbmri-eric:ID:EXT_ACU
2. Click the `< Back` link

### Expected behavior
You will be sent to the home page (https://directory.bbmri-eric.eu/#/)

### Observed behavior
You navigate to the literal previous page (probably this one).

**Comment by mswertz** [comment]
kind of works as intended? Otherwise we should also rename to 'go to biobank list' or something.

**Comment by tommydeboer** [comment]
Right now there is no way to get to the home page without manipulating the URL. That doesn't seem right to me.

**Comment by jelmerveen** [comment]
It works as intended 'within' the app. Coming from external source directly wasn't a use-case.
I think we need a bread-crumb system to help solve both problems

**Comment by jelmerveen** [comment]
breadcrumb introduced in last update.
