### ISSUE TITLE
Loading & Blocking of filters

### ISSUE THREAD

**Issue by Pacific89** [molgenis/molgenis-app-biobank-explorer#375]
### How to reproduce
After choosing a filteroption, the filter menue is hidden since all filters are blocken/inactivated

### Expected Behaviour
The current filter stays active / is not deactivated
only other filters (except the one that is used at a certain moment) are blocked

### How to reproduce
Filter for two options of one filter (E.G. two countries), filter is deacivated after checking the first checkbox

**Comment by jelmerveen** [comment]
I think we need a little delay after selecting a checkbox, so that you can check multiple checkboxes before the query.
Also then disable the checkboxes, instead of the dropdowns so that the menu does not close.
