### ISSUE TITLE
separate the collections from he first line in the cards view

### ISSUE THREAD

**Issue by mrymsadeghi** [molgenis/molgenis-app-biobank-explorer#386]
The information about the number of collections available (e.g. “9 collections available”) in the Biobank cards is too close to the first single collection. Some users found it difficult to understand if the 9 available collections were part of this first result (the first collection displayed). In this example, the collection is also called the same as the biobank itself (“HCV Research UK”).

 Integrate a separator between “(n) collections available” and the first collection. Suggestion: Add a horizontal line just like all the other listed collections

![image](https://user-images.githubusercontent.com/42934556/197587548-63bdd6a6-c9cc-4441-83c2-a8662606ec2c.png)

**Comment by jelmerveen** [comment]
Implemented
