### ISSUE TITLE
Add unit and e2e tests

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-app-biobank-explorer#39]
## Unit tests
This project has an average of 75% unit coverage. We decided to have at least 80% coverage. Add component tests would cover also branches in our VUE components.

## End to End tests
The project does include an e2e test but it does not provide dummy data and only checks that the body gets rendered.

Would be nice if something a little more substantial got tested.

**Comment by jelmerveen** [comment]
Coverage is above 80% nowadays. E2E tests are done manually for now.
