### ISSUE TITLE
Biobanks without collections are shown again

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-app-biobank-explorer#44]
### How to Reproduce
Go to biobank explorer

### Expected behavior
I only see biobanks with collections

### Observed behavior
I see all biobanks, also without collections

**Comment by fdlk** [comment]
I discussed this with @mswertz and if you ave no filters this is the desired behavior.

**Comment by djvanenckevort** [comment]
This has been resolved in the current version.
