### ISSUE TITLE
Biobank Explorer not showing results when only token is specified and no search criteria

### ISSUE THREAD

**Issue by reihsr** [molgenis/molgenis-app-biobank-explorer#47]
This is for the new BBMRI-ERIC Negotiator connection, where it will be possible to have multiple searches for the same negotiation. For this the negotiator sends the user to molgenis with only the negotiator token as the parameter for the url. 
http://d1.ref.development.bibbox.org/menu/main/apps/aaaacyrfnu2ymascvqjaabiaai/biobankexplorer?nToken=d6127989c64f457cae80924101b28764

### How to Reproduce
If there is a parameter at the url that is not a search valid field it will show no results. when adding a search parameter, it shows the correct result. 

URL not working:
http://d1.ref.development.bibbox.org/menu/main/apps/aaaacyrfnu2ymascvqjaabiaai/biobankexplorer?nToken=d6127989c64f457cae80924101b28764
URL working:
http://d1.ref.development.bibbox.org/menu/main/apps/aaaacyrfnu2ymascvqjaabiaai/biobankexplorer?nToken=d6127989c64f457cae80924101b28764&country=AT

### Expected behavior
The explorer should show the unfiltered list of all biobanks. 

### Observed behavior
The explorer shows "No biobanks were found".

**Comment by sidohaakma** [comment]
Hi,

We have fixed this in the next production version (2.1.0). https://registry.molgenis.org/repository/appstore/molgenis-app-biobank-explorer/2.1.0/molgenis-app-biobank-explorer.zip.

With molgenis platform version 7.1.0 (https://oss.sonatype.org/service/local/repositories/releases/content/org/molgenis/molgenis-app/7.1.0-RELEASE/molgenis-app-7.1.0-RELEASE.war).

Could you verify this?

Kind regards,

Sido

**Comment by jelmerveen** [comment]
Closing this, because no reply was given in two years.
