### ISSUE TITLE
Spaces in diagnosis available search not working

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-app-biobank-explorer#49]
### How to Reproduce
Type in diagnosis available search: Malignant n

### Expected behavior
I get Malignant neoplasms

### Observed behavior
Error!

Search query should have "

**Comment by fdlk** [comment]
Suggestion for the fix: use rsql library to format and encode the search query

**Comment by marikaris** [comment]
I'm going to look into it, thanks!

**Comment by marikaris** [comment]
The rsql library does not put quotes around the query

**Comment by fdlk** [comment]
The encoder escapes them.
