### ISSUE TITLE
Version number in config.js generated during build does not match version number in repository

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis-app-biobank-explorer#75]
### How to Reproduce
Go to the [Repository](https://registry.molgenis.org/#browse/browse:appstore:molgenis-app-biobank-explorer) and download one of the zip archives

### Expected behavior
The app version in the config.js inside the zip archive matched the version on the Repository ( part of repository path).

### Observed behavior
The app version in the config.js inside the zip archive does not match the version on the Repository.

**Comment by jelmerveen** [comment]
This is no longer an issue
