### ISSUE TITLE
Infinite loop if collection is its own parent

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-app-biobank-explorer#76]
### How to Reproduce
Update a collection and set its parent to itself

### Expected behavior
A warning or it just works

### Observed behavior
Infinite spinner loading biobanks

**Comment by fdlk** [comment]
As a workaround you can find them using `select id, acronym, parent_collection from "eu_bbmri_eric_collections#4dc023e6" where parent_collection = id;`

**Comment by jelmerveen** [comment]
Closing this for now
