### ISSUE TITLE
Biobank explorer does not show the quality marks for sub collections

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis-app-biobank-explorer#83]
### How to Reproduce
Search for Collection quality Marks: BBMRI-ERIC audited (https://directory.bbmri-eric.eu/menu/main/app-molgenis-app-biobank-explorer/biobankexplorer?collection_quality=eric)

### Expected behavior
Sub collections, such as the collection 'Genomic DNA in Long Term Storage Collection' should show quality marks

### Observed behavior
The collection 'Genomic DNA in Long Term Storage Collection' does not show quality marks, but does match the search.

<img width="1012" alt="schermafbeelding 2019-02-21 om 12 13 57" src="https://user-images.githubusercontent.com/1942445/53165187-595a3880-35d2-11e9-9738-46520bcd6534.png">

**Comment by connoratrug** [comment]
PR with fix awaiting review https://github.com/molgenis/molgenis-app-biobank-explorer/pull/87
