### ISSUE TITLE
When editing search criteria of a request in the Negotiator the "Go to sample / data negotiation" button is active but clicking on it does not do anything.

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis-app-biobank-explorer#86]
### How to Reproduce
- https://negotiator.bbmri-eric.eu/researcher/newQuery.xhtml?queryId=74
- BBMRI-ERIC Directory - Free text search contains mmci  -> Edit Search Parameters
- this transfers the user to the Directory
- select only collections that have quality mark:
- Clicking the "Go to sample / data negotiation" is active, can be clicked, shows gray border around the button while clicking it, but does not do anything after that.

### Expected behavior
When editing search criteria of a request in the Negotiator, after tranferred back to Directory, the "Go to sample / data negotiation" button is active and when I click on it I'm transferred to the Negotiator again

### Observed behavior
When editing search criteria of a request in the Negotiator, after being transferred back to Directory, the "Go to sample / data negotiation" button is active but clicking on it does not do anything.

**Comment by connoratrug** [comment]
Can not reproduce ( when is click the button i am transferred), please add more details and exact steps. Please consider adding screen shots or mail me a screen grap directly and i will look into it.

**Comment by djvanenckevort** [comment]
The issue is a duplicate nToken returned by the Negotiator and will be resolved in the Negotiator.
